### ISSUE TITLE
Move tickets from RT over here

### ISSUE THREAD

**Issue by petdance** [libwww-perl/HTML-Tagset#8]
Assuming that the libwww-perl org wants to have this GitHub repo be the home of issues, there are 5 tickets in https://rt.cpan.org/Public/Dist/Display.html?Name=HTML-Tagset that you'll probably want to move over.

**Comment by PhilterPaper** [comment]
Yes, the tickets should be closed on RT  (mod Makefille.PL to point to here) and anything still open brought over here. The RT system's future isn't certain, the interface is clunky, and we're not notified up updates. Right now it is possible to open tickets on both RT and GH; the former should be shut down to minimize confusion.

Who is going to move the tickets over? It's not a huge job, but I wouldn't be surprised if many of the ticket owners are no longer on the system. If there's only a handful of tickets, I will volunteer to reopen a few of them over here, if you and perhaps @castaway will split the rest of them. Would you assign tickets to move?

**Comment by PhilterPaper** [comment]
I seem to be locked out (403 Forbidden) from updating the remaining RT tickets, so I opened #9 (RT 109044) here. If you can, Andy, please close tickets on RT as they're opened here. Unless someone beats me to it, I'll migrate tickets from time to time.

**Comment by petdance** [comment]
I closed the ticket that @PhilterPaper could not and I migrated and closed the remaining tickets.
